[book]
title = "Pulsate Development Guide"
description = "A guide to developing the Pulsate"
src = "guide"
language = "ja"
authors = ["Pulsate Project Team"]

[build]
build-dir = "build"
create-missing = false
use-default-templates = true

[output.html]
git-repository-url = "https://github.com/pulsate-dev/dev-guide"
edit-url-template = "https://github.com/pulsate-dev/dev-guide/edit/main/{path}"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.alerts]

